["Ricobenes", "Nevermore", "Crisp", "Marias Packaged Goods", "Aloha Eats",
    "Pacos Tacos", "Noodles in the Pot", "Falcos", "Connies", "Empty Bottle",
    "Schubas", "Twin Anchors", "Reggies", "Tonic", "Kingston Mines",
    "Estelles", "Oiistar", "Als Taylor", "Marios Italian Ice", "Express Grill",
    "Reckless Records", "Margies Candies", "Atotonilcos", "Emporium", "Kincades",
    "Moneygun", "Wolfys", "Moodys Pub", "Eddie V's", "Carnitas Don Rafa",
    "Lawrence Fish Market", "Ping Pong", "Cafe Bionda", "Heaven on 7", "Roost",
    "Cherry Circle Room", "Millers Pub", "Onward", "The Gage", "Bandera", "Bavettes",
    "The Green Mill", "Yoshis", "Wildberry Cafe", "Demera", "Beatrix", "The Purple Pig",
    "Elizabeth", "Calo Ristorante"]